#pragma once

/*-----------------------------------------------------------
 * ServoController Driver Interface
 *
 * This class provides an abstraction layer for controlling
 * servo motors used to open doors and windows in the system.
 *
 * Servo motors are typically driven using PWM signals
 * generated by a hardware timer (e.g., TIM1 on STM32).
 *
 * Responsibilities:
 * - Control door servo position
 * - Control window servo position
 * - Provide a clean interface to the application layer
 *
 * Note:
 * The underlying PWM timer must be initialized and started
 * during system initialization (e.g., HAL_TIM_PWM_Start).
 *----------------------------------------------------------*/
class ServoController
{
public:

    /*-------------------------------------------------------
     * openDoors()
     *
     * Moves the door servo to the predefined "open" position
     * by updating the PWM duty cycle for the corresponding
     * timer channel.
     *
     * This function should be non-blocking and safe to call
     * from RTOS tasks.
     *------------------------------------------------------*/
    void openDoors() noexcept;

    /*-------------------------------------------------------
     * openWindows()
     *
     * Moves the window servo to the predefined "open" position
     * by updating the PWM duty cycle for the corresponding
     * timer channel.
     *
     * The exact PWM value depends on servo calibration.
     *------------------------------------------------------*/
    void openWindows() noexcept;
};
